copyright: cc-by
remote_branch: master
site_name: maximool's learning the web
site_description: if that's possible a little piece of Humanity too
site_author: maximool
theme:
  # https://squidfunk.github.io/mkdocs-material
  name: 'material'
  # palette:
  #   primary: 'Blue Grey'
  #   accent: 'Teal'
  font:
    text: 'Droid Sans'
    code: 'Monospace'
extra_css:
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  # https://squidfunk.github.io/mkdocs-material/customization/#additional-css
  - stylesheets/extra.css
